# Generated by Django 4.0.3 on 2022-05-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='User Id')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('imagePfp', models.ImageField(blank=True, max_length=255, null=True, upload_to='perfil/', verbose_name='Imagen de perfil')),
                ('rol', models.IntegerField(blank=True, verbose_name='User role')),
                ('fechaNac', models.CharField(max_length=30, verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=30, verbose_name='Fecha de nacimiento')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Bio/Descripcion')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
