# Generated by Django 4.0.3 on 2022-05-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_mod_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.IntegerField(verbose_name='User role'),
        ),
    ]
