# Generated by Django 4.0.3 on 2022-05-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=9, verbose_name='users DNI'),
        ),
    ]
