# Generated by Django 4.0.3 on 2022-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='users DNI'),
        ),
    ]
