# Generated by Django 4.0.3 on 2022-05-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bio/Descripcion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaNac',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
