# Generated by Django 4.0.3 on 2022-06-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagePfp',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='static/usersPfp/', verbose_name='Imagen de perfil'),
        ),
    ]
