# Generated by Django 4.0.3 on 2022-06-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_imagepfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagePfp',
            field=models.ImageField(blank=True, null=True, upload_to='static/usersPfp/', verbose_name='Imagen de perfil'),
        ),
    ]
