# Generated by Django 4.0.3 on 2022-05-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Post Id')),
                ('userid', models.IntegerField(verbose_name='User Id')),
                ('tema', models.CharField(max_length=50, unique=True, verbose_name='Tema Post')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo Post')),
                ('tipoPost', models.IntegerField(verbose_name='Tipo de post')),
                ('contenido', models.CharField(max_length=255, verbose_name='Contenido del post')),
                ('rutaImgPost', models.ImageField(blank=True, max_length=255, null=True, upload_to='imgPost/', verbose_name='Imagen de perfil')),
            ],
        ),
    ]
