# Generated by Django 4.0.3 on 2022-05-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id Tema')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tema nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id Tipo Post')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo Post nombre')),
            ],
        ),
    ]
