# Generated by Django 4.0.3 on 2022-05-28 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_post_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.tema'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tipoPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.tipopost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
