# Generated by Django 4.0.3 on 2022-05-28 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_post_tema_alter_post_tipopost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relateds', to=settings.AUTH_USER_MODEL),
        ),
    ]
