# Generated by Django 4.0.3 on 2022-06-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rutaImgPost',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Imagen de perfil'),
        ),
    ]
